// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASbU2EF7vDYf9uShtiEE_ke_1omgMGD6A',
    appId: '1:617690526724:web:bf55fd9eb5863e96d13151',
    messagingSenderId: '617690526724',
    projectId: 'chainapp-15225',
    authDomain: 'chainapp-15225.firebaseapp.com',
    storageBucket: 'chainapp-15225.firebasestorage.app',
    measurementId: 'G-4H4J7BX8NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD55SaVtn2sWCVJ-B4d0wqPpW61eKBtXxI',
    appId: '1:617690526724:android:b012b728ee3c3210d13151',
    messagingSenderId: '617690526724',
    projectId: 'chainapp-15225',
    storageBucket: 'chainapp-15225.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPrrKfSKhrm72yOkabHcayJcPUPHZwM5s',
    appId: '1:617690526724:ios:9144a3f2c5154a8dd13151',
    messagingSenderId: '617690526724',
    projectId: 'chainapp-15225',
    storageBucket: 'chainapp-15225.firebasestorage.app',
    iosBundleId: 'com.example.chainapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPrrKfSKhrm72yOkabHcayJcPUPHZwM5s',
    appId: '1:617690526724:ios:9144a3f2c5154a8dd13151',
    messagingSenderId: '617690526724',
    projectId: 'chainapp-15225',
    storageBucket: 'chainapp-15225.firebasestorage.app',
    iosBundleId: 'com.example.chainapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASbU2EF7vDYf9uShtiEE_ke_1omgMGD6A',
    appId: '1:617690526724:web:faf175c298f641d0d13151',
    messagingSenderId: '617690526724',
    projectId: 'chainapp-15225',
    authDomain: 'chainapp-15225.firebaseapp.com',
    storageBucket: 'chainapp-15225.firebasestorage.app',
    measurementId: 'G-ZL9L33QEBH',
  );
}
